baseurl = "https://piotrek-k.pl"
title = "piotrek-k.pl"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Piotr Kozerski"
  info = ".NET Developer"
  description = "Portfolio"
  keywords = "portfolio,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2022

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = ["css/styles.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

  [params.theme]
  palette = "gruvbox-dark"
  mode = "dark-mode"

  # Sidebar: about/bio
  [params.about]
  title = "Links"
  description = ""

  [[params.socialLinks]]
  icon = "fab fa-github"
  title = "GitHub"
  url = "https://github.com/piotrek-k"

  [[params.socialLinks]]
  icon = "fas fa-envelope"
  title = "Email"
  url = "mailto:inbox+website@kozer.ski"

  [[params.socialLinks]]
  icon = "fab fa-linkedin"
  title = "LinkedIn"
  url = "https://www.linkedin.com/in/piotr-kozerski/"

  [[params.socialLinks]]
  icon = "fab fa-stack-overflow"
  title = "StackOverflow"
  url = "https://stackoverflow.com/users/1804027/piotrek"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[menu]

  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 3

# necessary to render raw HTML
[markup.goldmark.renderer]
unsafe= true